version: '3.3'

services:
  db:
    image: mysql:8.0.26
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql